version: "3.7"

services:
  redis:
    image: redis:5
    restart: on-failure
    expose:
      - 6379

  frontend:
    restart: on-failure
    build:
      context: frontend/
    environment:
      VUE_APP_WEBSOCKET_SERVER_URL: ws://127.0.0.1:7500
    depends_on:
      - backend
    ports:
      - "8080:8080"

  backend:
    restart: on-failure
    build:
      context: backend/
      args:
        SECRET_KEY: "${SECRET_KEY-testkey}"
    environment:
      REDIS_IP: redis
      SECRET_KEY: "${SECRET_KEY-testkey}"
      DJANGO_SETTINGS_MODULE: weeapps.settings.prod
    depends_on:
      - redis
    ports:
      - "7500:8000"
