# Generated by Django 2.2.5 on 2019-10-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("color", models.CharField(blank=True, max_length=30)),
                ("does_expire", models.BooleanField(default=False)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
            ],
        )
    ]
