# Generated by Django 2.2.6 on 2019-10-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='does_expire',
        ),
    ]
